### ISSUE TITLE
wzrd.in/standalone fails for packages depending on AngularJS

### ISSUE THREAD

**Issue by YMIndustries** [jfhbrook/wzrd.in#161] opened 2017-02-28 05:09 UTC
For example, https://wzrd.in/standalone/angular-material@latest and https://wzrd.in/standalone/angular-moment@latest both fail with "browserify exited with code 1". The specific error message in each case is different.

**Comment by jfhbrook** [comment] 2017-02-28 19:35
Does angular depend on bundledDependencies? The latter, at least, looks like it could be a dupe of https://github.com/jfhbrook/wzrd.in/issues/130

**Comment by YMIndustries** [comment] 2017-02-28 19:37
I'm not sure. If I just get Angular, it works: https://wzrd.in/standalone/angular@latest

It's only things that depend on Angular that fail.

**Comment by jfhbrook** [comment] 2017-02-28 22:56
right--they most likely expect angular to be installed separately.

I'm going to close this issue as a dupe of #130 since that's really what this sounds like, but feel free to dig further and prove me wrong!

**Closed by jfhbrook** 2017-02-28 22:56 UTC
