### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by qgustavor** [jfhbrook/wzrd.in#160] opened 2017-02-04 21:01 UTC
The current wzrd.in certificate expired today, 04/02/17 15:35. I find it a bit strange, considering it uses Let's Encrypt. Does the auto-renew failed?

**Comment by voronianski** [comment] 2017-02-04 23:03
@jfhbrook experiencing this too

**Comment by jfhbrook** [comment] 2017-02-04 23:04
Yeah, should be fixed. I think the cron job was busted. Manually ran the renew command and updated the cron job.

Sorry for the delay.

**Closed by jfhbrook** 2017-02-04 23:04 UTC

**Comment by voronianski** [comment] 2017-02-04 23:11
@jfhbrook something is wrong with cors:

```
XMLHttpRequest cannot load https://wzrd.in/multi. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://esnextb.in' is therefore not allowed access.
```

**Comment by jfhbrook** [comment] 2017-02-04 23:35
I, uh

that sounds unrelated. Can you find me on irc? freenode, this nick. I can help you triage for the next hour or so (I have a dinner) and also get you box access.

**Comment by jfhbrook** [comment] 2017-02-04 23:38
Doing some basic curling, it appears that CORS headers don't show up on erroring routes, maybe this route is having a different error of some kind? Can you get me the payload that's trying to send?

**Comment by jfhbrook** [comment] 2017-02-04 23:41
@voronianski ^^ we should talk about this in real time

**Comment by jfhbrook** [comment] 2017-02-04 23:43
I've repro'd:

```
$ curl -i -X POST -d '{"dependencies":{"concat-stream":"latest"}}' https://wzrd.in/multi

HTTP/1.1 200 OK
Server: nginx/1.11.3
Date: Sat, 04 Feb 2017 23:42:36 GMT
Content-Type: application/json
Content-Length: 75359
Connection: keep-alive
X-Powered-By: Express
Location: /multi/959f91479a56b2276933705b60e10843
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

**Comment by jfhbrook** [comment] 2017-02-04 23:47
This appears to be a problem on all cors stuff, so the issue is with the middleware and not the route:

```
$ curl -i https://wzrd.in/standalne/concat-stream@latest | less
```

**Comment by jfhbrook** [comment] 2017-02-04 23:48
Hey, I think I fixed it! The CORS middleware was at the wrong stage?

**Comment by jfhbrook** [comment] 2017-02-04 23:50
Get ahold of me anyway though @voronianski I can get you access to the box

**Comment by voronianski** [comment] 2017-02-05 02:12
@jfhbrook thanks for fixing! I will reach you out tomorrow in irc. I'm going to sleep now as it's late night in my timezone ;)
