### ISSUE TITLE
browserify exited with code 1

### ISSUE THREAD

**Issue by tommoor** [jfhbrook/wzrd.in#169] opened 2017-05-07 02:23 UTC
Thanks for creating this service! I haven't been able to get a request from requirebin to work today, I've tried with various versions of React set but always seems to be variations of the following or a 504 Gateway Timeout.

### Request
```javascript
{
  "options":{"debug":true},
  "dependencies":{"react":"*","react-dom":"*","emojione-picker":"2.2"}
}
```

### Response

```
---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: 98e00ea0-32cb-11e7-8cb0-132801c92ed4 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react/lib/ReactDOM' from '/tmp/react-dom11747-27730-1txvb55/node_modules/react-dom'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

dirPath: /tmp/react-dom11747-27730-1txvb55


--- error #1: ---


(logs uuid: 98e05cc0-32cb-11e7-8cb0-132801c92ed4 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'prop-types' from '/tmp/emojione-picker11747-27730-3ucrs6/node_modules/emojione-picker/lib'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

dirPath: /tmp/emojione-picker11747-27730-3ucrs6

```

**Comment by jfhbrook** [comment] 2017-05-07 02:56
This sounds like a peerDependencies issue. Those don't work. I'll find the issue.

**Comment by jfhbrook** [comment] 2017-05-07 02:57
https://github.com/jfhbrook/wzrd.in/issues/130

**Comment by jfhbrook** [comment] 2017-05-07 02:57
Basic testing, ie https://wzrd.in/standalone/concat-stream@latest suggests this isn't a regression.

Closing as a dupe, barring proof that this is different.

Sorry :/

**Closed by jfhbrook** 2017-05-07 02:57 UTC

**Comment by tommoor** [comment] 2017-05-07 02:59
I understand you have to keep the issues under control! The package I'm importing has no peerDependencies though: https://github.com/tommoor/emojione-picker/blob/master/package.json

Unless you're suggesting that React / ReactDOM does and those can't be used with wzrd.in ? Seems like that would disallow quite a lot of usecases nowadays.

**Comment by jfhbrook** [comment] 2017-05-07 03:03
Yes, that is indeed the case--react modules effectively treat each other as peer dependencies.

**Comment by jfhbrook** [comment] 2017-05-07 03:04
It's a fairly major limitation, I agree! But it would require a pretty big refactor to support this, due to a deep-seated design assumption (that peerDeps are rare).

If you're interested in fixing this, try to find me in irc (#node.js is as good a place as any) and we can talk about next steps.

**Comment by jfhbrook** [comment] 2017-05-07 03:09
emoji-picker, fwiw, succeeds for me.
